# Generated by Django 5.0.1 on 2024-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.IntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=1),
        ),
    ]
